In [3]:
import numpy as np
list1 = np.array([1,2,3])
list2 = np.array([2,3,4])
print(list1 + list2)
print(list1.ndim)#维度
print(list1.shape)
print(list1.size)
print(list1.dtype)#类型

[3 5 7]
1
(3,)
3
int64


In [4]:
import numpy as np

# 1. 创建全 0 数组：这里创建一个 2 行 4 列的全 0 矩阵
zeros_array = np.zeros((2, 4))
print("--- 1. 全 0 数组 ---")
print(zeros_array)
print()  

# 2. 创建全 1 数组：创建一个 3 行 2 列的全 1 矩阵
ones_array = np.ones((3, 2))
print("--- 2. 全 1 数组 ---")
print(ones_array)
print()

# 3. 创建空数组：创建一个包含 4 个元素的一维空数组（里面是内存垃圾值）
empty_array = np.empty(4)
print("--- 3. 空数组（随机值） ---")
print(empty_array)
print()

# 4. 创建等差数列：从 5 开始，到 20 结束（不含20），步长为 3
arange_array = np.arange(5, 20, 3)
print("--- 4. 等差数列数组 ---")
print(arange_array)
print()

# 5. 使用 Python 循环：让 i 从 1 变到 5（不含6），循环打印
print("--- 5. for 循环输出 ---")
for i in range(1, 6):
    print(f"当前循环次数 i = {i}")

--- 1. 全 0 数组 ---
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

--- 2. 全 1 数组 ---
[[1. 1.]
 [1. 1.]
 [1. 1.]]

--- 3. 空数组（随机值） ---
[0. 0. 0. 0.]

--- 4. 等差数列数组 ---
[ 5  8 11 14 17]

--- 5. for 循环输出 ---
当前循环次数 i = 1
当前循环次数 i = 2
当前循环次数 i = 3
当前循环次数 i = 4
当前循环次数 i = 5
