In [32]:
import numpy as np
feng = np.array([1,2,3,4,5])
print(type(feng))
print(feng)
#就是相当于向量加一
print(feng + 1)
print(feng ** 2)
#构造多维数组
xin = np.array([[1,2,3,4,5]
               ,[2,3,4,5,6]])
print(feng.shape)
print(xin.shape)

<class 'numpy.ndarray'>
[1 2 3 4 5]
[2 3 4 5 6]
[ 1  4  9 16 25]
(5,)
(5,)
(2, 5)


In [19]:
print(feng[2])

3


In [27]:
#查看向量数字的类型,只能是相同类型，如果不是相同类型，会向下兼容
print(feng.dtype)
print(xin.dtype)

int64
int64


In [26]:
print(feng.itemsize)

8


In [33]:
print(feng.size,xin.size)

5 10


In [36]:
#查看维度
print(feng.ndim,xin.ndim)

1 2


In [38]:
#填充为0
xin.fill(0)
print(xin)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [48]:
#切片还有索引
print(feng[2:],feng[-2:-1])
print(xin[1:2])
#多维的切片，中间用逗号隔 开
print(xin[0:1,3:])
print(xin[1,2])
#还可以赋值修改
xin[1,2] = 10000
print(xin)

[3 4 5] [4]
[[    0     0 10000     0     0]]
[[0 0]]
10000
[[    0     0     0     0     0]
 [    0     0 10000     0     0]]


In [53]:
zeng = feng
print(zeng)
zeng[1] = 10
print(feng)
print(zeng)
#说明这个zeng和feng都是指向同一个地址
#怎么解决,使用深拷贝
zeng = feng.copy

[ 1 10  3  4  5]
[ 1 10  3  4  5]
[ 1 10  3  4  5]


In [66]:
#构造等差数组,左开右闭的
feng = np.arange(1,10,2)
print(feng)
mask = np.array([1,0,0,0,0,0,1],dtype = bool)
print(mask)

[1 3 5 7 9]
[ True False False False False False  True]


In [70]:
#随机数,从0到1中间随机出十个数字
random_num = np.random.rand(10)
print(random_num)

[0.24775113 0.50091914 0.32858687 0.82688391 0.88504158 0.89165132
 0.22083946 0.85446576 0.70552234 0.52093175]


In [74]:
np.where(feng > 5)
feng > 30

array([False, False, False, False, False])

In [79]:
#指定类型
zeng  = np.array([1,2,3,4],dtype = np.float32)
zeng.nbytes

16