In [32]:
import numpy as np
feng = np.array([1,2,3,4,5])
print(type(feng))
print(feng)
#就是相当于向量加一
print(feng + 1)
print(feng ** 2)
#构造多维数组
xin = np.array([[1,2,3,4,5]
               ,[2,3,4,5,6]])
print(feng.shape)
print(xin.shape)

<class 'numpy.ndarray'>
[1 2 3 4 5]
[2 3 4 5 6]
[ 1  4  9 16 25]
(5,)
(5,)
(2, 5)


In [19]:
print(feng[2])

3


In [27]:
#查看向量数字的类型,只能是相同类型，如果不是相同类型，会向下兼容
print(feng.dtype)
print(xin.dtype)

int64
int64


In [26]:
print(feng.itemsize)

8


In [33]:
print(feng.size,xin.size)

5 10


In [36]:
#查看维度
print(feng.ndim,xin.ndim)

1 2


In [38]:
#填充为0
xin.fill(0)
print(xin)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [48]:
#切片还有索引
print(feng[2:],feng[-2:-1])
print(xin[1:2])
#多维的切片，中间用逗号隔 开
print(xin[0:1,3:])
print(xin[1,2])
#还可以赋值修改
xin[1,2] = 10000
print(xin)

[3 4 5] [4]
[[    0     0 10000     0     0]]
[[0 0]]
10000
[[    0     0     0     0     0]
 [    0     0 10000     0     0]]


In [53]:
zeng = feng
print(zeng)
zeng[1] = 10
print(feng)
print(zeng)
#说明这个zeng和feng都是指向同一个地址
#怎么解决,使用深拷贝
zeng = feng.copy

[ 1 10  3  4  5]
[ 1 10  3  4  5]
[ 1 10  3  4  5]


In [66]:
#构造等差数组,左开右闭的
feng = np.arange(1,10,2)
print(feng)
mask = np.array([1,0,0,0,0,0,1],dtype = bool)
print(mask)

[1 3 5 7 9]
[ True False False False False False  True]


In [70]:
#随机数,从0到1中间随机出十个数字
random_num = np.random.rand(10)
print(random_num)

[0.24775113 0.50091914 0.32858687 0.82688391 0.88504158 0.89165132
 0.22083946 0.85446576 0.70552234 0.52093175]


In [74]:
np.where(feng > 5)
feng > 30

array([False, False, False, False, False])

In [79]:
#指定类型
zeng  = np.array([1,2,3,4],dtype = np.float32)
zeng.nbytes

16

In [36]:
import numpy as np
feng = np.array([[1,2,3,4,5,6,7,8],
                [2,3,4,5,6,7,5,4]])
feng.sum()
feng.sum(axis = 0)
feng.sum(axis = 1)
feng.min()
feng.max()
feng.var()
feng.std()
feng.prod()
feng.argmin()
feng.argmax()
feng.sort()
xin = np.array([1,2,4])
feng.mean
feng.clip(1,3)
xin = np.array([1.23,1.23,1.34])
xin.round(decimals = 1)
np.linspace(1,10,3)
feng.reshape(4,4)
feng[ : ,np.newaxis]
feng.squeeze()

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 4, 5, 5, 6, 7]])

In [58]:
feng.T
#array数组的连接
feng = np.array([[1,2,3,4,5],
               [12,23,34,23,12]])
xin = np.array([[12,12,23,34,45],
              [12,34,45,56,67]])
#feng = np.concatenate((feng,xin))
#feng

#zeng = np.concatenate((feng,xin),axis = 1)
#zeng.shape
feng.shape
np.vstack((feng,xin))
np.hstack((feng,xin))

feng = np.array([[1,2,3],
               [2,3,4]])

In [73]:
#数组生成函数
np.arange(0,9,2)
np.arange(10)
np.arange(1,20,3,dtype = np.float32)
np.linspace(100,300)
#logspace用来生成指数
np.logspace(1,3,num = 3,base = 1.2)

#网格
x = np.linspace(-10,10,5)
y = np.linspace(-10,10,5)
x,y = np.meshgrid(x,y)
x,y

(array([[-10.,  -5.,   0.,   5.,  10.],
        [-10.,  -5.,   0.,   5.,  10.],
        [-10.,  -5.,   0.,   5.,  10.],
        [-10.,  -5.,   0.,   5.,  10.],
        [-10.,  -5.,   0.,   5.,  10.]]),
 array([[-10., -10., -10., -10., -10.],
        [ -5.,  -5.,  -5.,  -5.,  -5.],
        [  0.,   0.,   0.,   0.,   0.],
        [  5.,   5.,   5.,   5.,   5.],
        [ 10.,  10.,  10.,  10.,  10.]]))

In [82]:
np.r_[0:10:2]
np.c_[0:10:2]

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [113]:
#常用生成函数
feng = np.zeros(3)
feng[ : ,np.newaxis]
feng.squeeze()
np.zeros((3,3))
feng = np.ones((2,3),dtype = np.int32)
feng[0,1] = 3
np.ones((2,3)) * 2
#先占位置，内容全部都是垃圾值
x = np.empty(5)
x.fill(2)
x
x= np.array([0,1,2,3,4])
x
#容器一样，内容全部换成0
np.ones_like(x)*32
#np.zeros_like(x)

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [121]:
#四则运算
x = np.array([5,5])
y = np.array([2,2])
#对应位置相乘
np.multiply(x,y)
#矩阵相乘
np.dot(x,y)
x == y

array([False, False])

In [125]:
#逻辑与 &
np.logical_and(x,y)
#逻辑或 
np.logical_or(x,y)
#逻辑非
np.logical_not(x,y)

array([0, 0])

In [150]:
#随机模块
#所有的值都是0到1的
np.random.rand(3,2)
np.random.randint(3,20,size = (3,2))
np.random.random_sample()
np.random.randint(0,10,3)
#正态分布
mu,sigma = 0,0.1
np.random.normal(mu,sigma,10)

np.set_printoptions(precision = 3)
np.random.rand(3)

array([0.991, 0.523, 0.988])

In [155]:
#洗牌
feng = np.arange(0,10,2)
np.random.shuffle(feng)
feng

array([8, 2, 6, 0, 4])

In [161]:
#随机的种子
feng = np.random.seed()

In [ ]:
#